USE CobbleNameDemo;
GO


-- AddUser
-- Called by POST/api/users
-- Adds new users to the users Table 
-- Returns the ID generated by SQL SERVER for the new record.
CREATE PROCEDURE AddUser
    @Name NVARCHAR(255)
AS
BEGIN
    INSERT INTO Users (Name)
    VALUES (@Name);

    SELECT CAST(SCOPE_IDENTITY() AS INT) AS Id;
END;
GO

-- GetUsers 
-- Called by GET /api/users 
-- Retrieves all users currently stored in the users table 
-- Converts these rows to JSON for the react frontend 
CREATE PROCEDURE GetUsers
AS
BEGIN
    SELECT Id, Name
    FROM Users
    ORDER BY Id;
END;
GO